- task: aquasecScanner@4
  inputs:
    image: 'windowsimg/apache24:latest'
    scanType: 'hosted'
    register: false
    hideBase: false
    showNegligible: true
    windowsScannerVersion: '6.5.0'
    registry: 'https://hub.docker.com'
    connection: 'ihwinddowsado'
    showWillNotFix: true