# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    echo Hello, windows!
    docker pull windowsimg/apache24
- task: aquasecScanner@4
  inputs:
    image: 'windowsimg/apache24:latest'
    scanType: 'hosted'
    register: false
    hideBase: false
    showNegligible: true
    windowsScannerVersion: '6.5.0'
    registry: 'https://hub.docker.com'
    connection: 'ihwinddowsado'
    scanMalware: true
    showWillNotFix: true

- script: |
    echo SCAN DONE..
  displayName: 'CLOSING'
