# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    echo Hello, windows!
    docker pull windowsimg/apache24:latest
    docker login registry.aquasec.com -u $(AQUAUSER) -p $(AQUAUSERPASS)
    docker run -e BUILD_JOB_NAME=Apache_Windows --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --host https://225fccbcb7.cloud.aquasec.com/ --local test:v1 --token $(TOKEN) --layer-vulnerabilities --no-verify
  displayName: 'Pull and Scan'

- script: |
    echo SCAN DONE..
  displayName: 'CLOSING'
