name: Build and scan

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  aqua:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs docker build 
      - name: Build docker image
        run: docker pull windowsimg/apache24:latest

      # Aqua Registry login
      - name: Login to Aqua Registry
        uses: docker/login-action@v1
        with:
          registry: registry.aquasec.com
          username: ${{ secrets.AQUADEV_USERNAME }}
          password: ${{ secrets.AQUADEV_PASS }}
      
      
      # Scan the test Image
      - name: Run the scanner 
        run: |
          docker run -e BUILD_JOB_NAME=Apache_Windows -e BUILD_NUMBER=${{ github.run_id }} --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --host https://225fccbcb7.cloud.aquasec.com/ --local test:v1 --token ${{ secrets.TOKEN }} --layer-vulnerabilities --no-verify --html > .github/workflows/scan-output.html
    
   
